version: "3"

services:
  prom-server:
    image: prom/prometheus
    ports:
      - "9090:9090"  # Fixed port mapping format
    volumes:
      - ./prometheus-config.yml:/etc/prometheus/prometheus.yml  # Fixed volume path format
